# this an example for _LocalVariable.py

# directories  
_WORKING_DIRECTORY = ""
_DATA_DIRECTORY = ""


_TRAINED_MODEL_OUTPUT_DIRECTORY = _WORKING_DIRECTORY + r"\TrainedModelOutput"

_DATA_INPUT_DIRECTORY = _DATA_DIRECTORY + r"\Input"
_DATA_OUTPUT_DIRECTORY = _DATA_DIRECTORY + r"\Output"


# browser driver path
_FIREFOX_DRIVER_PATH = ""

# twitter api
_TWITTER_ACCESS_TOKEN = ""
_TWITTER_ACCESS_TOKEN_SECRET = ""
_TWITTER_CONSUMER_KEY = ""
_TWITTER_CONSUMER_SECRET = ""


